project_name: botkube
env:
  - IMAGE_REGISTRY={{ if index .Env "IMAGE_REGISTRY"  }}{{ .Env.IMAGE_REGISTRY }}{{ else }}ghcr.io{{ end }}
  - IMAGE_REPOSITORY={{ if index .Env "IMAGE_REPOSITORY"  }}{{ .Env.IMAGE_REPOSITORY }}{{ else }}pkosiec/botkube{{ end }}
  - TEST_IMAGE_REPOSITORY={{ if index .Env "TEST_IMAGE_REPOSITORY"  }}{{ .Env.TEST_IMAGE_REPOSITORY }}{{ else }}pkosiec/botkube-test{{ end }}
before:
  hooks:
    - go mod download
builds:
  - id: botkube
    binary: botkube
    main: cmd/botkube/main.go
    ldflags: &ldflags
      - -s -w
        -X github.com/infracloudio/botkube/pkg/version.Version={{ .Tag }}
        -X github.com/infracloudio/botkube/pkg/version.GitCommitID={{ .Commit }}
        -X github.com/infracloudio/botkube/pkg/version.BuildDate={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  skip: true
dockers:
  - image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: "build/Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=botkube_version={{ .Tag }}"
  - image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Tag }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: "build/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=botkube_version={{ .Tag }}"
  - image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Tag }}-armv7"
    use: buildx
    goarch: arm
    goarm: 7
    dockerfile: "build/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm"
      - "--build-arg=botkube_version={{ .Tag }}"
  - image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.TEST_IMAGE_REPOSITORY}}:{{ .Tag }}"
    use: buildx
    dockerfile: "build/test.Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm"
      - "--build-arg=TEST_NAME=e2e"
docker_manifests:
  - name_template: "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Tag }}"
    image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Tag }}-amd64"
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Tag }}-arm64"
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Tag }}-armv7"
